// Comprehensive mock data for Admin Dashboard - Test System
// Applications / Sorting: Urbco Foundry and Urbco Harbor
// Stages: Before Development and After Development

export const mockUser = {
  id: "user-001",
  email: "admin@urbcofoundry.com",
  name: "Admin User",
  role: "ADMIN",
  phone: "+234 801 234 5678",
  timezone: "Africa/Lagos",
  dateFormat: "DD/MM/YYYY",
  currency: "NGN",
  emailNotifications: true,
  pushNotifications: true,
  transactionAlerts: true,
  weeklyReports: true,
  agentUpdates: true,
};

export const mockCompanies = [
  {
    id: "comp-001",
    serialId: "COM-001",
    name: "Urbco Developments Ltd",
    type: "developer",
    registrationNumber: "RC-123456",
    status: "active",
    contactPerson: "Adebayo Ogundimu",
    email: "contact@urbco.com",
    phone: "+234 802 345 6789",
    address: "14 Marina Road, Victoria Island, Lagos",
    agreementStartDate: "2024-01-15",
    agreementExpiryDate: "2025-01-15",
    commissionRate: 5,
    paymentTerms: "Full payment within the next 30 days",
    notes: "Premium partner",
    bankName: "First Bank of Nigeria",
    accountNumber: "0123456789",
    bankAccountName: "Urbco Developments Ltd",
    totalAssets: 12,
    activeAssets: 8,
    totalTransactions: 45,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "comp-002",
    serialId: "COM-002",
    name: "Lagos Premium Estates",
    type: "realtor",
    registrationNumber: "RC-234567",
    status: "active",
    contactPerson: "Funke Adeyemi",
    email: "info@lagospremium.com",
    phone: "+234 803 456 7890",
    address: "22 Lekki Phase 1, Lagos",
    agreementStartDate: "2024-02-20",
    agreementExpiryDate: "2025-02-20",
    commissionRate: 4,
    paymentTerms: "Full payment within the next 60 days",
    notes: "",
    bankName: "GTBank",
    accountNumber: "0234567890",
    bankAccountName: "Lagos Premium Estates",
    totalAssets: 8,
    activeAssets: 5,
    totalTransactions: 32,
    createdAt: "2024-02-20T14:30:00Z",
  },
  {
    id: "comp-003",
    serialId: "COM-003",
    name: "Abuja Luxury Homes",
    type: "partner",
    registrationNumber: "RC-345678",
    status: "pending",
    contactPerson: "Ibrahim Musa",
    email: "sales@abujaluxury.com",
    phone: "+234 804 567 8901",
    address: "Plot 45, Maitama, Abuja",
    agreementStartDate: "2024-03-10",
    agreementExpiryDate: "2025-03-10",
    commissionRate: 6,
    paymentTerms: "Full payment immediately",
    notes: "New partner onboarding",
    bankName: "Zenith Bank",
    accountNumber: "0345678901",
    bankAccountName: "Abuja Luxury Homes",
    totalAssets: 6,
    activeAssets: 4,
    totalTransactions: 18,
    createdAt: "2024-03-10T09:15:00Z",
  },
];

// Urbco Foundry Assets & Urbco Harbor Assets
export const mockAssets = [
  {
    id: "asset-001",
    platform: "Urbco Foundry",
    developmentStage: "Before Development",
    name: "Marina Heights Tower A",
    referenceCode: "MHT-A-2024",
    type: "Off Plan",
    projectStatus: "Foundation",
    location: "Victoria Island, Lagos",
    address: "Plot 1234, Marina Road, Victoria Island",
    companyId: "comp-001",
    company: { id: "comp-001", name: "Urbco Developments Ltd" },
    landSize: "5000",
    builtSize: "45000",
    constructionStart: "2024-06-01",
    constructionEnd: "2026-12-31",
    propertyCategory: "Residential",
    totalUnits: 156,
    availableUnits: 142,
    unitConfiguration: "1 Bedroom, 2 Bedrooms, 3 Bedrooms",
    furnished: "Unfurnished",
    facilities: ["Pool", "Gym", "Parking", "Security", "Spa"],
    facilityManagement: true,
    ownershipType: "Fractional",
    buyingPaths: ["Investment"],
    fractionTotal: 1000,
    fractionCost: 5000000,
    price: 5000000000,
    markup: 750000000,
    paymentOptions: ["Outright", "Installment"],
    installmentPeriods: ["6 months", "12 months", "24 months"],
    downPaymentAmount: 1500000000,
    offPlanDiscount: 10,
    stageBasedDiscount: 5,
    projectedRentalIncome: 450000000,
    rentalFrequency: "Annual",
    operatingCost: 100000000,
    capitalAppreciation: 15,
    firstPayoutDate: "2027-01-01",
    rentalYieldMin: 7.5,
    rentalYieldMax: 9.2,
    capitalAppreciationMin: 12,
    capitalAppreciationMax: 18,
    totalReturnsMin: 19.5,
    totalReturnsMax: 27.2,
    constructionStage: 25,
    riskLevel: "Medium",
    riskFactors: ["Market volatility", "Construction delays"],
    offPlanSecurity: "Bank Guarantee",
    exitLiquidity: "High",
    managementMode: "Urbco Foundry-managed",
    images: 12,
    documents: 5,
    virtualTours: 1,
    leadCommission: 2.5,
    closerCommission: 1.5,
    status: "active",
    createdAt: "2024-04-01T10:00:00Z",
  },
  {
    id: "asset-002",
    platform: "Urbco Foundry",
    developmentStage: "After Development",
    name: "Lekki Phase 1 Estate",
    referenceCode: "LPE-2024",
    type: "Completed",
    projectStatus: "Available",
    location: "Lekki, Lagos",
    address: "Block 45, Lekki Phase 1",
    companyId: "comp-002",
    company: { id: "comp-002", name: "Lagos Premium Estates" },
    landSize: "3000",
    builtSize: "28000",
    propertyCategory: "Residential",
    totalUnits: 48,
    availableUnits: 12,
    unitConfiguration: "3 Bedrooms, 4 Bedrooms, 5 Bedrooms",
    furnished: "Fully furnished",
    facilities: ["Pool", "Gym", "Parking", "Security", "Private Beach"],
    facilityManagement: true,
    ownershipType: "Full",
    buyingPaths: ["Ownership"],
    titleTerms:
      "Title deed transfers within 60 days of final payment; occupancy rights from handover.",
    price: 8500000000,
    markup: 1275000000,
    paymentOptions: ["Outright"],
    projectedRentalIncome: 680000000,
    rentalFrequency: "Annual",
    operatingCost: 150000000,
    capitalAppreciation: 12,
    rentalYieldMin: 6.8,
    rentalYieldMax: 8.5,
    capitalAppreciationMin: 10,
    capitalAppreciationMax: 15,
    totalReturnsMin: 16.8,
    totalReturnsMax: 23.5,
    constructionStage: 100,
    riskLevel: "Low",
    riskFactors: [],
    exitLiquidity: "High",
    managementMode: "Urbco Foundry-managed",
    images: 24,
    documents: 8,
    virtualTours: 2,
    leadCommission: 3,
    closerCommission: 2,
    status: "active",
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "asset-003",
    platform: "Urbco Foundry",
    developmentStage: "After Development",
    name: "Abuja Commercial Plaza",
    referenceCode: "ACP-2024",
    type: "Under Construction",
    projectStatus: "Under Construction",
    location: "Central Business District, Abuja",
    address: "Plot 789, CBD Abuja",
    companyId: "comp-003",
    company: { id: "comp-003", name: "Abuja Luxury Homes" },
    landSize: "8000",
    builtSize: "65000",
    constructionStart: "2024-03-01",
    constructionEnd: "2025-09-30",
    propertyCategory: "Commercial",
    totalUnits: 200,
    availableUnits: 185,
    unitConfiguration: "Office Space, Retail Space",
    furnished: "N/A",
    facilities: ["Parking", "Security", "Elevators", "Meeting Rooms"],
    facilityManagement: true,
    ownershipType: "Fractional",
    buyingPaths: ["Investment", "Ownership"],
    releaseBasis: "Milestone-linked",
    milestones: [
      { name: "Structure completed", targetDate: "2024-03-15", releasePct: "30" },
      { name: "External works finished", targetDate: "2024-07-01", releasePct: "40" },
      { name: "Fit-out & handover ready", targetDate: "2024-09-01", releasePct: "30" },
    ],
    titleTerms:
      "Title deed transfers within 60 days of final payment; occupancy rights from handover.",
    fractionTotal: 5000,
    fractionCost: 2000000,
    price: 10000000000,
    markup: 1500000000,
    paymentOptions: ["Outright", "Installment"],
    installmentPeriods: ["12 months", "24 months", "36 months"],
    downPaymentAmount: 3000000000,
    offPlanDiscount: 15,
    projectedRentalIncome: 900000000,
    rentalFrequency: "Annual",
    operatingCost: 200000000,
    capitalAppreciation: 18,
    firstPayoutDate: "2025-10-01",
    rentalYieldMin: 8.2,
    rentalYieldMax: 10.5,
    capitalAppreciationMin: 15,
    capitalAppreciationMax: 22,
    totalReturnsMin: 23.2,
    totalReturnsMax: 32.5,
    constructionStage: 60,
    riskLevel: "Medium",
    riskFactors: ["Regulatory changes", "Economic downturn"],
    offPlanSecurity: "Insurance Bond",
    exitLiquidity: "Medium",
    managementMode: "Urbco Foundry-managed",
    images: 18,
    documents: 12,
    virtualTours: 1,
    leadCommission: 2,
    closerCommission: 1.5,
    status: "active",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "asset-004",
    platform: "Urbco Foundry",
    developmentStage: "Before Development",
    name: "Ibeju-Lekki Land Parcel",
    referenceCode: "ILL-2024",
    type: "Land",
    projectStatus: "Available",
    location: "Ibeju-Lekki, Lagos",
    address: "Km 25, Lekki-Epe Expressway",
    companyId: "comp-001",
    company: { id: "comp-001", name: "Urbco Developments Ltd" },
    landSize: "50000",
    ownershipType: "Fractional",
    buyingPaths: ["Investment"],
    fractionTotal: 10000,
    fractionCost: 500000,
    landUnitType: "sqm",
    landUnitCount: 50000,
    price: 5000000000,
    markup: 1000000000,
    paymentOptions: ["Outright", "Installment"],
    installmentPeriods: ["6 months", "12 months"],
    downPaymentAmount: 1500000000,
    capitalAppreciation: 25,
    capitalAppreciationMin: 20,
    capitalAppreciationMax: 35,
    totalReturnsMin: 20,
    totalReturnsMax: 35,
    constructionStage: 100,
    riskLevel: "Low",
    riskFactors: [],
    exitLiquidity: "High",
    managementMode: "Self-managed",
    images: 8,
    documents: 4,
    leadCommission: 3,
    closerCommission: 2,
    status: "active",
    createdAt: "2024-05-01T10:00:00Z",
  },
  // Urbco Harbor Assets - pre-development/inception stage projects
  {
    id: "asset-005",
    platform: "Urbco Harbor",
    developmentStage: "Before Development",
    name: "Eko Atlantic Waterfront City",
    referenceCode: "URB-ECO-2024",
    type: "Off Plan",
    projectStatus: "Planning",
    location: "Eko Atlantic, Lagos",
    address: "Victoria Island Extension, Lagos",
    companyId: "comp-001",
    company: { id: "comp-001", name: "Urbco Developments Ltd" },
    landSize: "120000",
    builtSize: "250000",
    constructionStart: "2025-01-01",
    constructionEnd: "2028-06-30",
    propertyCategory: "Mixed-use",
    targetCompletion: "2028-06-30",
    totalInvestmentRequired: 50000000000,
    buyingPaths: ["Investment"],
    investmentWindowStart: "2025-01-01",
    investmentWindowEnd: "2026-06-30",
    investorRights:
      "Pro-rata voting rights on major decisions, quarterly reporting, information rights.",
    redemptionTerms:
      "12-month holding period, then 30-day redemption notice with quarterly liquidity windows.",
    currentFunding: 12000000000,
    fundingProgress: 24,
    minimumInvestment: 10000000,
    expectedROI: 35,
    projectedReturns: 45,
    investmentType: "Equity",
    investorCount: 48,
    riskLevel: "High",
    riskFactors: ["Regulatory approval pending", "Infrastructure dependency", "Market timing"],
    permits: ["Environmental Impact Assessment - Pending", "Building Plan - Not Submitted"],
    exitLiquidity: "Low",
    managementMode: "Urbco Harbor-managed",
    images: 5,
    documents: 15,
    virtualTours: 0,
    status: "active",
    createdAt: "2024-06-01T10:00:00Z",
  },
  {
    id: "asset-006",
    platform: "Urbco Harbor",
    developmentStage: "Before Development",
    name: "Ibeju-Lekki Industrial Estate",
    referenceCode: "URB-ILE-2024",
    type: "Off Plan",
    projectStatus: "Land Acquisition",
    location: "Ibeju-Lekki, Lagos",
    address: "Free Trade Zone, Ibeju-Lekki",
    companyId: "comp-001",
    company: { id: "comp-001", name: "Urbco Developments Ltd" },
    landSize: "500000",
    targetCompletion: "2029-12-31",
    totalInvestmentRequired: 100000000000,
    buyingPaths: ["Investment"],
    currentFunding: 25000000000,
    fundingProgress: 25,
    minimumInvestment: 5000000,
    expectedROI: 40,
    projectedReturns: 55,
    investmentType: "Equity",
    investorCount: 72,
    riskLevel: "High",
    riskFactors: ["Land title verification", "Government policy changes", "Long development timeline"],
    permits: ["Governor's Consent - In Progress", "Survey Plan - Completed"],
    exitLiquidity: "Low",
    managementMode: "Urbco Harbor-managed",
    images: 3,
    documents: 20,
    virtualTours: 0,
    status: "active",
    createdAt: "2024-07-01T10:00:00Z",
  },
];

export const mockClusters = [
  {
    id: "cluster-001",
    serialId: "CLR-001",
    code: "LAG-ALP",
    name: "Lagos Alpha",
    description: "Lagos-based sales cluster A",
    location: "Lagos, Nigeria",
    teamLeadId: "user-002",
    managerId: "user-002",
    teamLead: "John Smith",
    agentCount: 8,
    agents: 8,
    totalLeads: 45,
    closedDeals: 12,
    activeAssets: 5,
    totalRevenue: 450000000,
    totalCommission: 22500000,
    status: "ACTIVE",
    commissionType: "AGENT",
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "cluster-002",
    serialId: "CLR-002",
    code: "LAG-BET",
    name: "Lagos Beta",
    description: "Lagos-based sales cluster B",
    location: "Lagos, Nigeria",
    teamLeadId: "user-003",
    managerId: "user-003",
    teamLead: "Sarah Johnson",
    agentCount: 6,
    agents: 6,
    totalLeads: 38,
    closedDeals: 9,
    activeAssets: 3,
    totalRevenue: 320000000,
    totalCommission: 16000000,
    status: "ACTIVE",
    commissionType: "CLUSTER",
    bankName: "Access Bank",
    accountName: "Lagos Beta Cluster Account",
    accountNumber: "0456789012",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "cluster-003",
    serialId: "CLR-003",
    code: "ABJ-PRM",
    name: "Abuja Prime",
    description: "Abuja-based sales cluster",
    location: "Abuja, Nigeria",
    teamLeadId: "user-004",
    managerId: "user-004",
    teamLead: "Michael Brown",
    agentCount: 5,
    agents: 5,
    totalLeads: 32,
    closedDeals: 8,
    activeAssets: 4,
    totalRevenue: 280000000,
    totalCommission: 14000000,
    status: "ACTIVE",
    commissionType: "AGENT",
    createdAt: "2024-02-01T10:00:00Z",
  },
];

export const mockAgents = [
  {
    id: "agent-001",
    serialId: "AGT-001",
    name: "David Wilson",
    email: "david.wilson@buyops.com",
    phone: "+234 805 678 9012",
    clusterId: "cluster-001",
    cluster: "Lagos Alpha",
    role: "AGENT",
    status: "ACTIVE",
    activeDeals: 5,
    closedDeals: 12,
    totalCommission: 18500000,
    commissionRate: 3.5,
    performance: 120,
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "agent-002",
    serialId: "AGT-002",
    name: "Emma Davis",
    email: "emma.davis@buyops.com",
    phone: "+234 806 789 0123",
    clusterId: "cluster-001",
    cluster: "Lagos Alpha",
    role: "AGENT",
    status: "ACTIVE",
    activeDeals: 3,
    closedDeals: 8,
    totalCommission: 12000000,
    commissionRate: 3.0,
    performance: 95,
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "agent-003",
    serialId: "AGT-003",
    name: "James Taylor",
    email: "james.taylor@buyops.com",
    phone: "+234 807 890 1234",
    clusterId: "cluster-002",
    cluster: "Lagos Beta",
    role: "AGENT",
    status: "ACTIVE",
    activeDeals: 4,
    closedDeals: 10,
    totalCommission: 15000000,
    commissionRate: 3.2,
    performance: 110,
    createdAt: "2024-02-10T10:00:00Z",
  },
  {
    id: "agent-004",
    serialId: "AGT-004",
    name: "Olivia Martinez",
    email: "olivia.martinez@buyops.com",
    phone: "+234 808 901 2345",
    clusterId: "cluster-003",
    cluster: "Abuja Prime",
    role: "AGENT",
    status: "PENDING",
    activeDeals: 2,
    closedDeals: 5,
    totalCommission: 7500000,
    commissionRate: 2.8,
    performance: 85,
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "user-002",
    serialId: "TL-001",
    name: "John Smith",
    email: "john.smith@buyops.com",
    phone: "+234 809 012 3456",
    clusterId: "cluster-001",
    cluster: "Lagos Alpha",
    role: "TEAM_LEAD",
    status: "ACTIVE",
    activeDeals: 8,
    closedDeals: 25,
    totalCommission: 42000000,
    commissionRate: 4.0,
    performance: 145,
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "user-003",
    serialId: "TL-002",
    name: "Sarah Johnson",
    email: "sarah.johnson@buyops.com",
    phone: "+234 810 123 4567",
    clusterId: "cluster-002",
    cluster: "Lagos Beta",
    role: "TEAM_LEAD",
    status: "ACTIVE",
    activeDeals: 6,
    closedDeals: 20,
    totalCommission: 35000000,
    commissionRate: 4.0,
    performance: 130,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "user-004",
    serialId: "TL-003",
    name: "Michael Brown",
    email: "michael.brown@buyops.com",
    phone: "+234 811 234 5678",
    clusterId: "cluster-003",
    cluster: "Abuja Prime",
    role: "TEAM_LEAD",
    status: "ACTIVE",
    activeDeals: 5,
    closedDeals: 18,
    totalCommission: 30000000,
    commissionRate: 4.0,
    performance: 125,
    createdAt: "2024-02-01T10:00:00Z",
  },
];

export const mockFreelancers = [
  {
    id: "freelancer-001",
    name: "Alex Thompson",
    email: "alex.thompson@email.com",
    phone: "+234 812 345 6789",
    status: "active",
    totalLeads: 15,
    closedDeals: 4,
    totalCommission: 6000000,
    commissionRate: 2.0,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "freelancer-002",
    name: "Rachel Green",
    email: "rachel.green@email.com",
    phone: "+234 813 456 7890",
    status: "active",
    totalLeads: 10,
    closedDeals: 2,
    totalCommission: 3500000,
    commissionRate: 2.0,
    createdAt: "2024-04-01T10:00:00Z",
  },
];

export const mockLeads = [
  {
    id: "lead-001",
    serialId: "LEAD-001",
    name: "Robert Anderson",
    email: "robert.anderson@email.com",
    phone: "+234 814 567 8901",
    assetInterest: "Marina Heights Tower A",
    asset: { id: "asset-001", name: "Marina Heights Tower A", platform: "Urbco Foundry" },
    budget: 25000000,
    source: "investor-app",
    leadSource: "investor-app",
    status: "pending",
    assignedTo: null,
    assignedCluster: null,
    dateReceived: "2024-05-01T10:00:00Z",
  },
  {
    id: "lead-002",
    serialId: "LEAD-002",
    name: "Jennifer White",
    email: "jennifer.white@email.com",
    phone: "+234 815 678 9012",
    assetInterest: "Lekki Phase 1 Estate",
    asset: { id: "asset-002", name: "Lekki Phase 1 Estate", platform: "Urbco Foundry" },
    budget: 45000000,
    source: "investor-app",
    leadSource: "investor-app",
    status: "assigned",
    assignedTo: { id: "agent-001", name: "David Wilson" },
    assignedCluster: "cluster-001",
    dateReceived: "2024-04-28T10:00:00Z",
  },
  {
    id: "lead-003",
    serialId: "LEAD-003",
    name: "Thomas Harris",
    email: "thomas.harris@email.com",
    phone: "+234 816 789 0123",
    assetInterest: "Abuja Commercial Plaza",
    asset: { id: "asset-003", name: "Abuja Commercial Plaza", platform: "Urbco Foundry" },
    budget: 15000000,
    source: "agent",
    leadSource: "agent",
    createdBy: { id: "agent-001", name: "David Wilson" },
    status: "assigned",
    assignedTo: { id: "agent-001", name: "David Wilson" },
    assignedCluster: "cluster-001",
    dateReceived: "2024-04-25T10:00:00Z",
  },
  {
    id: "lead-004",
    serialId: "LEAD-004",
    name: "Patricia Clark",
    email: "patricia.clark@email.com",
    phone: "+234 817 890 1234",
    assetInterest: "Ibeju-Lekki Land Parcel",
    asset: { id: "asset-004", name: "Ibeju-Lekki Land Parcel", platform: "Urbco Foundry" },
    budget: 8000000,
    source: "investor-app",
    leadSource: "investor-app",
    status: "available",
    assignedTo: null,
    assignedCluster: null,
    dateReceived: "2024-05-02T10:00:00Z",
  },
  {
    id: "lead-005",
    serialId: "LEAD-005",
    name: "Daniel Lewis",
    email: "daniel.lewis@email.com",
    phone: "+234 818 901 2345",
    assetInterest: "Eko Atlantic Waterfront City",
    asset: { id: "asset-005", name: "Eko Atlantic Waterfront City", platform: "Urbco Harbor" },
    budget: 35000000,
    source: "freelancer",
    leadSource: "freelancer",
    createdBy: { id: "freelancer-001", name: "Alex Thompson" },
    status: "assigned",
    assignedTo: { id: "freelancer-001", name: "Alex Thompson" },
    assignedCluster: null,
    dateReceived: "2024-04-20T10:00:00Z",
  },
  {
    id: "lead-006",
    serialId: "LEAD-006",
    name: "Lisa Walker",
    email: "lisa.walker@email.com",
    phone: "+234 819 012 3456",
    assetInterest: "Lekki Phase 1 Estate",
    asset: { id: "asset-002", name: "Lekki Phase 1 Estate", platform: "Urbco Foundry" },
    budget: 55000000,
    source: "team-lead",
    leadSource: "team-lead",
    createdBy: { id: "user-002", name: "John Smith" },
    status: "assigned",
    assignedTo: { id: "user-002", name: "John Smith" },
    assignedCluster: "cluster-001",
    dateReceived: "2024-04-18T10:00:00Z",
  },
];

export const mockTransactions = [
  {
    id: "txn-001",
    serialId: "TXN-2024-001",
    assetId: "asset-001",
    assetName: "Marina Heights Tower A",
    assetPlatform: "Urbco Foundry",
    buyerName: "Robert Anderson",
    buyerEmail: "robert.anderson@email.com",
    buyerId: "inv-001",
    amount: 25000000,
    paidAmount: 10000000,
    outstandingAmount: 15000000,
    paymentType: "installment",
    commission: 1000000,
    commissionStatus: "unpaid",
    status: "completed",
    paymentMethod: "bank_transfer",
    date: "2024-05-01T10:00:00Z",
    agentId: "agent-001",
    agentName: "David Wilson",
  },
  {
    id: "txn-002",
    serialId: "TXN-2024-002",
    assetId: "asset-002",
    assetName: "Lekki Phase 1 Estate",
    assetPlatform: "Urbco Foundry",
    buyerName: "Jennifer White",
    buyerEmail: "jennifer.white@email.com",
    buyerId: "inv-002",
    amount: 45000000,
    paidAmount: 45000000,
    outstandingAmount: 0,
    paymentType: "one-time",
    commission: 1800000,
    commissionStatus: "paid",
    status: "completed",
    paymentMethod: "paystack",
    date: "2024-04-28T10:00:00Z",
    agentId: "agent-001",
    agentName: "David Wilson",
  },
  {
    id: "txn-003",
    serialId: "TXN-2024-003",
    assetId: "asset-003",
    assetName: "Abuja Commercial Plaza",
    assetPlatform: "Urbco Foundry",
    buyerName: "Thomas Harris",
    buyerEmail: "thomas.harris@email.com",
    buyerId: "inv-003",
    amount: 15000000,
    paidAmount: 5000000,
    outstandingAmount: 10000000,
    paymentType: "installment",
    commission: 525000,
    commissionStatus: "unpaid",
    status: "pending",
    paymentMethod: "flutterwave",
    date: "2024-04-25T10:00:00Z",
    agentId: "agent-003",
    agentName: "James Taylor",
  },
  {
    id: "txn-004",
    serialId: "TXN-2024-004",
    assetId: "asset-004",
    assetName: "Ibeju-Lekki Land Parcel",
    assetPlatform: "Urbco Foundry",
    buyerName: "Patricia Clark",
    buyerEmail: "patricia.clark@email.com",
    buyerId: "inv-004",
    amount: 8000000,
    paidAmount: 8000000,
    outstandingAmount: 0,
    paymentType: "one-time",
    commission: 400000,
    commissionStatus: "unpaid",
    status: "completed",
    paymentMethod: "bank_transfer",
    date: "2024-05-02T10:00:00Z",
    agentId: "agent-002",
    agentName: "Emma Davis",
  },
  {
    id: "txn-005",
    serialId: "TXN-2024-005",
    assetId: "asset-005",
    assetName: "Eko Atlantic Waterfront City",
    assetPlatform: "Urbco Harbor",
    buyerName: "Adebayo Ogunlesi",
    buyerEmail: "adebayo.ogunlesi@email.com",
    buyerId: "inv-005",
    amount: 50000000,
    paidAmount: 20000000,
    outstandingAmount: 30000000,
    paymentType: "installment",
    commission: 2000000,
    commissionStatus: "unpaid",
    status: "active",
    paymentMethod: "bank_transfer",
    date: "2024-06-15T10:00:00Z",
    agentId: "agent-001",
    agentName: "David Wilson",
  },
  {
    id: "txn-006",
    serialId: "TXN-2024-006",
    assetId: "asset-006",
    assetName: "Ibeju-Lekki Industrial Estate",
    assetPlatform: "Urbco Harbor",
    buyerName: "Chioma Nwosu",
    buyerEmail: "chioma.nwosu@email.com",
    buyerId: "inv-006",
    amount: 25000000,
    paidAmount: 10000000,
    outstandingAmount: 15000000,
    paymentType: "installment",
    commission: 1000000,
    commissionStatus: "unpaid",
    status: "active",
    paymentMethod: "bank_transfer",
    date: "2024-07-10T10:00:00Z",
    agentId: "agent-003",
    agentName: "James Taylor",
  },
];

export const mockInstallmentPlans = [
  {
    id: "installment-001",
    transactionId: "txn-001",
    buyerName: "Robert Anderson",
    assetName: "Marina Heights Tower A",
    assetPlatform: "Urbco Foundry",
    totalAmount: 25000000,
    paidAmount: 10000000,
    remainingAmount: 15000000,
    status: "active",
    period: "12 months",
    monthlyPayment: 1250000,
    nextPaymentDate: "2024-06-01T10:00:00Z",
    installments: [
      { id: "inst-001", dueDate: "2024-05-01T10:00:00Z", amount: 1250000, status: "paid", paidDate: "2024-05-01T10:00:00Z" },
      { id: "inst-002", dueDate: "2024-06-01T10:00:00Z", amount: 1250000, status: "upcoming" },
      { id: "inst-003", dueDate: "2024-07-01T10:00:00Z", amount: 1250000, status: "upcoming" },
    ],
  },
  {
    id: "installment-002",
    transactionId: "txn-005",
    buyerName: "Adebayo Ogunlesi",
    assetName: "Eko Atlantic Waterfront City",
    assetPlatform: "Urbco Harbor",
    totalAmount: 50000000,
    paidAmount: 20000000,
    remainingAmount: 30000000,
    status: "active",
    period: "24 months",
    monthlyPayment: 1250000,
    nextPaymentDate: "2024-07-15T10:00:00Z",
    installments: [
      { id: "inst-004", dueDate: "2024-06-15T10:00:00Z", amount: 10000000, status: "paid", paidDate: "2024-06-15T10:00:00Z" },
      { id: "inst-005", dueDate: "2024-07-15T10:00:00Z", amount: 10000000, status: "upcoming" },
      { id: "inst-006", dueDate: "2024-08-15T10:00:00Z", amount: 10000000, status: "upcoming" },
    ],
  },
];

// Investors/Users with platform segmentation
export const mockUsers = [
  {
    id: "user-001",
    name: "Admin User",
    email: "admin@urbcofoundry.com",
    role: "ADMIN",
    status: "ACTIVE",
    phone: "+234 801 234 5678",
    clusterId: null,
    investorPlatform: null,
    createdAt: "2024-01-01T10:00:00Z",
  },
  ...mockAgents.map((agent) => ({
    id: agent.id,
    userId: agent.id,
    name: agent.name,
    email: agent.email,
    role: agent.role,
    status: agent.status,
    phone: agent.phone,
    clusterId: agent.clusterId,
    investorPlatform: null,
    createdAt: agent.createdAt,
  })),
];

// Investors (separate from agents/team leads)
export const mockInvestors = [
  {
    id: "inv-001",
    name: "Robert Anderson",
    email: "robert.anderson@email.com",
    phone: "+234 814 567 8901",
    investorPlatform: "Urbco Foundry",
    totalInvested: 25000000,
    totalPaid: 10000000,
    outstandingBalance: 15000000,
    paymentType: "installment",
    assets: [{ assetId: "asset-001", assetName: "Marina Heights Tower A", platform: "Urbco Foundry", invested: 25000000, paid: 10000000, outstanding: 15000000 }],
    status: "active",
    createdAt: "2024-04-01T10:00:00Z",
    entityType: "individual",
    investorTrack: "foundry",
    kycStatus: "verified",
    kycSubmittedAt: "2024-04-02T09:30:00Z",
    kycVerifiedAt: "2024-04-05T14:00:00Z",
    kycRemediationItems: [],
    kycLastRemindedAt: null,
    kycProfile: {
      nationalId: "12345678901",
      bvn: "2222222222",
      residentialAddress: "12 Admiralty Way, Lekki Phase 1, Lagos",
    },
    kycDeclarations: {
      sourceOfFunds: "Executive Salary / Investment Income",
      targetTrack: "foundry",
    },
    kycDocuments: [
      { id: "doc-001-1", entityType: "individual", name: "Government Photo ID", fileUrl: "/kyc/robert-anderson/passport.pdf", status: "approved" },
      { id: "doc-001-2", entityType: "individual", name: "Live Biometric Selfie", fileUrl: "/kyc/robert-anderson/selfie.jpg", status: "approved" },
      { id: "doc-001-3", entityType: "individual", name: "Proof of Address", fileUrl: "/kyc/robert-anderson/utility-bill.pdf", status: "approved" },
      { id: "doc-001-4", entityType: "individual", name: "Accreditation Questionnaire", fileUrl: "/kyc/robert-anderson/questionnaire.pdf", status: "approved" },
    ],
  },
  {
    id: "inv-002",
    name: "Jennifer White",
    email: "jennifer.white@email.com",
    phone: "+234 815 678 9012",
    investorPlatform: "Urbco Foundry",
    totalInvested: 45000000,
    totalPaid: 45000000,
    outstandingBalance: 0,
    paymentType: "one-time",
    assets: [{ assetId: "asset-002", assetName: "Lekki Phase 1 Estate", platform: "Urbco Foundry", invested: 45000000, paid: 45000000, outstanding: 0 }],
    status: "active",
    createdAt: "2024-03-15T10:00:00Z",
    entityType: "individual",
    investorTrack: "foundry",
    kycStatus: "under_review",
    kycSubmittedAt: "2024-03-16T10:45:00Z",
    kycVerifiedAt: null,
    kycRemediationItems: [],
    kycLastRemindedAt: null,
    kycProfile: {
      nationalId: "98765432109",
      bvn: "3333333333",
      residentialAddress: "5 Ozumba Mbadiwe Avenue, Victoria Island, Lagos",
    },
    kycDeclarations: {
      sourceOfFunds: "Business Proceeds / Dividends",
      targetTrack: "foundry",
    },
    kycDocuments: [
      { id: "doc-002-1", entityType: "individual", name: "Government Photo ID", fileUrl: "/kyc/jennifer-white/drivers-license.pdf", status: "pending" },
      { id: "doc-002-2", entityType: "individual", name: "Live Biometric Selfie", fileUrl: "/kyc/jennifer-white/selfie.jpg", status: "pending" },
      { id: "doc-002-3", entityType: "individual", name: "Proof of Address", fileUrl: "/kyc/jennifer-white/bank-statement.pdf", status: "pending" },
      { id: "doc-002-4", entityType: "individual", name: "Accreditation Questionnaire", fileUrl: "/kyc/jennifer-white/questionnaire.pdf", status: "pending" },
    ],
  },
  {
    id: "inv-003",
    name: "Thomas Harris",
    email: "thomas.harris@email.com",
    phone: "+234 816 789 0123",
    investorPlatform: "Urbco Foundry",
    totalInvested: 15000000,
    totalPaid: 5000000,
    outstandingBalance: 10000000,
    paymentType: "installment",
    assets: [{ assetId: "asset-003", assetName: "Abuja Commercial Plaza", platform: "Urbco Foundry", invested: 15000000, paid: 5000000, outstanding: 10000000 }],
    status: "active",
    createdAt: "2024-04-10T10:00:00Z",
    entityType: "individual",
    investorTrack: "foundry",
    kycStatus: "remediation_required",
    kycSubmittedAt: "2024-04-11T16:20:00Z",
    kycVerifiedAt: null,
    kycRemediationItems: [
      "Live Biometric Selfie — photo is blurry; re-upload holding your ID next to your face",
      "Proof of Address — utility bill / bank statement not uploaded (must be under 3 months old)",
    ],
    kycLastRemindedAt: "2024-04-12T09:00:00Z",
    kycProfile: {
      nationalId: "45678912304",
      bvn: "4444444444",
      residentialAddress: "23 Adjose Street, Surulere, Lagos",
    },
    kycDeclarations: {
      sourceOfFunds: "Savings / Salary",
      targetTrack: "foundry",
    },
    kycDocuments: [
      { id: "doc-003-1", entityType: "individual", name: "Government Photo ID", fileUrl: "/kyc/thomas-harris/national-id.pdf", status: "approved" },
      { id: "doc-003-2", entityType: "individual", name: "Live Biometric Selfie", fileUrl: "/kyc/thomas-harris/selfie-blur.jpg", status: "rejected", rejectReason: "Photo is blurry — re-upload holding ID next to face" },
      { id: "doc-003-3", entityType: "individual", name: "Proof of Address", fileUrl: null, status: "missing" },
      { id: "doc-003-4", entityType: "individual", name: "Accreditation Questionnaire", fileUrl: "/kyc/thomas-harris/questionnaire.pdf", status: "approved" },
    ],
  },
  {
    id: "inv-004",
    name: "Patricia Clark",
    email: "patricia.clark@email.com",
    phone: "+234 817 890 1234",
    investorPlatform: "Urbco Foundry",
    totalInvested: 8000000,
    totalPaid: 8000000,
    outstandingBalance: 0,
    paymentType: "one-time",
    assets: [{ assetId: "asset-004", assetName: "Ibeju-Lekki Land Parcel", platform: "Urbco Foundry", invested: 8000000, paid: 8000000, outstanding: 0 }],
    status: "active",
    createdAt: "2024-04-20T10:00:00Z",
    entityType: "family-office",
    investorTrack: "foundry",
    kycStatus: "under_review",
    kycSubmittedAt: "2024-04-21T11:10:00Z",
    kycVerifiedAt: null,
    kycRemediationItems: [],
    kycLastRemindedAt: null,
    kycProfile: {
      companyName: "Clark Family Office Ltd",
      rcNumber: "RC-1298410",
      companyAddress: "3 Glover Road, Ikoyi, Lagos",
      repName: "Patricia Clark",
      repEmail: "patricia.clark@email.com",
    },
    kycDeclarations: {
      declaredAumRange: "$50M - $100M AUM",
      targetTrack: "foundry",
    },
    kycDocuments: [
      { id: "doc-004-1", entityType: "family-office", name: "Articles of Incorporation", fileUrl: "/kyc/patricia-clark/articles.pdf", status: "pending" },
      { id: "doc-004-2", entityType: "family-office", name: "Trustee/Director Passports", fileUrl: "/kyc/patricia-clark/trustee-ids.pdf", status: "pending" },
      { id: "doc-004-3", entityType: "family-office", name: "Proof of AUM / Asset Scale", fileUrl: "/kyc/patricia-clark/audited-statement.pdf", status: "pending" },
      { id: "doc-004-4", entityType: "family-office", name: "Beneficial Ownership (UBO)", fileUrl: "/kyc/patricia-clark/ubo-register.pdf", status: "pending" },
    ],
  },
  {
    id: "inv-005",
    name: "Adebayo Ogunlesi",
    email: "adebayo.ogunlesi@email.com",
    phone: "+234 820 123 4567",
    investorPlatform: "Urbco Harbor",
    totalInvested: 50000000,
    totalPaid: 20000000,
    outstandingBalance: 30000000,
    paymentType: "installment",
    assets: [{ assetId: "asset-005", assetName: "Eko Atlantic Waterfront City", platform: "Urbco Harbor", invested: 50000000, paid: 20000000, outstanding: 30000000 }],
    status: "active",
    createdAt: "2024-06-01T10:00:00Z",
    entityType: "family-office",
    investorTrack: "harbor",
    kycStatus: "pending",
    kycSubmittedAt: null,
    kycVerifiedAt: null,
    kycRemediationItems: [],
    kycLastRemindedAt: "2024-06-05T11:00:00Z",
    kycProfile: {
      companyName: "Ogunlesi Holdings Ltd",
      rcNumber: "RC-1445092",
      companyAddress: "",
      repName: "Adebayo Ogunlesi",
      repEmail: "",
    },
    kycDeclarations: {
      declaredAumRange: "$10M - $50M AUM",
      targetTrack: "",
    },
    kycDocuments: [
      { id: "doc-005-1", entityType: "family-office", name: "Articles of Incorporation", fileUrl: "/kyc/adebayo-ogunlesi/articles.pdf", status: "pending" },
      { id: "doc-005-2", entityType: "family-office", name: "Trustee/Director Passports", fileUrl: null, status: "missing" },
      { id: "doc-005-3", entityType: "family-office", name: "Proof of AUM / Asset Scale", fileUrl: null, status: "missing" },
      { id: "doc-005-4", entityType: "family-office", name: "Beneficial Ownership (UBO)", fileUrl: null, status: "missing" },
    ],
  },
  {
    id: "inv-006",
    name: "Chioma Nwosu",
    email: "chioma.nwosu@email.com",
    phone: "+234 821 234 5678",
    investorPlatform: "Urbco Harbor",
    totalInvested: 25000000,
    totalPaid: 10000000,
    outstandingBalance: 15000000,
    paymentType: "installment",
    assets: [{ assetId: "asset-006", assetName: "Ibeju-Lekki Industrial Estate", platform: "Urbco Harbor", invested: 25000000, paid: 10000000, outstanding: 15000000 }],
    status: "active",
    createdAt: "2024-07-01T10:00:00Z",
    entityType: "individual",
    investorTrack: "harbor",
    kycStatus: "pending",
    kycSubmittedAt: null,
    kycVerifiedAt: null,
    kycRemediationItems: [],
    kycLastRemindedAt: null,
    kycProfile: {
      nationalId: "78912345607",
      bvn: "5555555555",
      residentialAddress: "17 Agbaoku Street, Opebi, Ikeja, Lagos",
    },
    kycDeclarations: {
      sourceOfFunds: "Tech Startup Equity Sale",
      targetTrack: "harbor",
    },
    kycDocuments: [
      { id: "doc-006-1", entityType: "individual", name: "Government Photo ID", fileUrl: null, status: "missing" },
      { id: "doc-006-2", entityType: "individual", name: "Live Biometric Selfie", fileUrl: null, status: "missing" },
      { id: "doc-006-3", entityType: "individual", name: "Proof of Address", fileUrl: null, status: "missing" },
      { id: "doc-006-4", entityType: "individual", name: "Accreditation Questionnaire", fileUrl: null, status: "missing" },
    ],
  },
  {
    id: "inv-007",
    name: "Emeka Obi",
    email: "emeka.obi@email.com",
    phone: "+234 822 345 6789",
    investorPlatform: "Urbco Harbor",
    totalInvested: 15000000,
    totalPaid: 15000000,
    outstandingBalance: 0,
    paymentType: "one-time",
    assets: [{ assetId: "asset-005", assetName: "Eko Atlantic Waterfront City", platform: "Urbco Harbor", invested: 15000000, paid: 15000000, outstanding: 0 }],
    status: "active",
    createdAt: "2024-06-10T10:00:00Z",
    entityType: "individual",
    investorTrack: "harbor",
    kycStatus: "failed",
    kycSubmittedAt: "2024-06-11T13:05:00Z",
    kycVerifiedAt: null,
    kycRemediationItems: [
      "Government Photo ID — passport expired 2023-11-02; upload a valid passport or NIN slip to continue",
    ],
    kycLastRemindedAt: null,
    kycProfile: {
      nationalId: "32165498703",
      bvn: "6666666666",
      residentialAddress: "9 Acme Road, Ogba, Ikeja, Lagos",
    },
    kycDeclarations: {
      sourceOfFunds: "Contracting Income",
      targetTrack: "harbor",
    },
    kycDocuments: [
      { id: "doc-007-1", entityType: "individual", name: "Government Photo ID", fileUrl: "/kyc/emeka-obi/expired-passport.pdf", status: "rejected", rejectReason: "Passport expired 2023-11-02 — upload a valid ID" },
      { id: "doc-007-2", entityType: "individual", name: "Live Biometric Selfie", fileUrl: "/kyc/emeka-obi/selfie.jpg", status: "approved" },
      { id: "doc-007-3", entityType: "individual", name: "Proof of Address", fileUrl: "/kyc/emeka-obi/utility-bill.pdf", status: "approved" },
      { id: "doc-007-4", entityType: "individual", name: "Accreditation Questionnaire", fileUrl: "/kyc/emeka-obi/questionnaire.pdf", status: "approved" },
    ],
  },
  {
    id: "inv-008",
    name: "Zenith Capital Partners",
    email: "kyc@zenithcapital.com",
    phone: "+234 823 456 7890",
    investorPlatform: "Urbco Foundry",
    totalInvested: 0,
    totalPaid: 0,
    outstandingBalance: 0,
    paymentType: "one-time",
    assets: [],
    status: "active",
    createdAt: "2024-08-01T09:00:00Z",
    entityType: "institution",
    investorTrack: "foundry",
    kycStatus: "under_review",
    kycSubmittedAt: "2024-08-05T10:30:00Z",
    kycVerifiedAt: null,
    kycRemediationItems: [],
    kycLastRemindedAt: null,
    kycProfile: {
      companyName: "Zenith Capital Partners Ltd",
      rcNumber: "RC-1182004",
      companyAddress: "1410 Akin Adesola Street, Victoria Island, Lagos",
      repName: "Grace Adeyemi",
      repEmail: "g.adeyemi@zenithcapital.com",
      institutionType: "Investment Managers & Funds",
      structure: "Real Estate Fund",
      aumRange: "₦50B–₦250B",
      horizon: "3–7 years",
      sectors: ["Commercial", "Infrastructure"],
      regulatoryStatus: "Regulated",
    },
    kycDeclarations: {},
    kycDocuments: [
      { id: "doc-008-1", entityType: "institution", name: "Articles of Incorporation", fileUrl: "/kyc/zenith-capital/articles.pdf", status: "pending" },
      { id: "doc-008-2", entityType: "institution", name: "Trustee/Director Passports", fileUrl: "/kyc/zenith-capital/director-ids.pdf", status: "pending" },
      { id: "doc-008-3", entityType: "institution", name: "Board Resolution Letter", fileUrl: "/kyc/zenith-capital/board-resolution.pdf", status: "pending" },
      { id: "doc-008-4", entityType: "institution", name: "Beneficial Ownership (UBO)", fileUrl: "/kyc/zenith-capital/ubo.pdf", status: "pending" },
      { id: "doc-008-5", entityType: "institution", name: "Corporate Registration & Tax ID", fileUrl: "/kyc/zenith-capital/cac-tin.pdf", status: "pending" },
      { id: "doc-008-6", entityType: "institution", name: "Officer / Director Identification", fileUrl: "/kyc/zenith-capital/officer-ids.pdf", status: "pending" },
      { id: "doc-008-7", entityType: "institution", name: "AML Compliance Certificate", fileUrl: "/kyc/zenith-capital/aml-cert.pdf", status: "pending" },
    ],
  },
  {
    id: "inv-009",
    name: "Meridian Pension Trust",
    email: "onboarding@meridianpension.com",
    phone: "+234 824 567 8901",
    investorPlatform: "Urbco Harbor",
    totalInvested: 0,
    totalPaid: 0,
    outstandingBalance: 0,
    paymentType: "one-time",
    assets: [],
    status: "active",
    createdAt: "2024-08-01T10:00:00Z",
    entityType: "institution",
    investorTrack: "harbor",
    kycStatus: "pending",
    kycSubmittedAt: null,
    kycVerifiedAt: null,
    kycRemediationItems: [],
    kycLastRemindedAt: "2024-08-12T08:00:00Z",
    kycProfile: {
      companyName: "Meridian Pension Trust",
      rcNumber: "RC-1057788",
      companyAddress: "27 Aguiyi Ironsi Street, Maitama, Abuja",
      repName: "Ibrahim Suleiman",
      repEmail: "",
      institutionType: "Pension Funds",
      structure: "",
      aumRange: "₦250B–₦1T",
      horizon: "7+ years",
      sectors: [],
      regulatoryStatus: "Regulated",
    },
    kycDeclarations: {},
    kycDocuments: [
      { id: "doc-009-1", entityType: "institution", name: "Articles of Incorporation", fileUrl: "/kyc/meridian-pension/articles.pdf", status: "pending" },
      { id: "doc-009-2", entityType: "institution", name: "Trustee/Director Passports", fileUrl: "/kyc/meridian-pension/trustee-ids.pdf", status: "pending" },
      { id: "doc-009-3", entityType: "institution", name: "Board Resolution Letter", fileUrl: "/kyc/meridian-pension/board-resolution.pdf", status: "pending" },
      { id: "doc-009-4", entityType: "institution", name: "Beneficial Ownership (UBO)", fileUrl: "/kyc/meridian-pension/ubo.pdf", status: "pending" },
      { id: "doc-009-5", entityType: "institution", name: "Corporate Registration & Tax ID", fileUrl: "/kyc/meridian-pension/cac-tin.pdf", status: "pending" },
      { id: "doc-009-6", entityType: "institution", name: "Officer / Director Identification", fileUrl: null, status: "missing" },
      { id: "doc-009-7", entityType: "institution", name: "AML Compliance Certificate", fileUrl: null, status: "missing" },
      { id: "doc-009-8", entityType: "institution", name: "Government Photo ID", fileUrl: null, status: "missing" },
      { id: "doc-009-9", entityType: "institution", name: "Live Biometric Selfie", fileUrl: null, status: "missing" },
      { id: "doc-009-10", entityType: "institution", name: "Proof of Address", fileUrl: null, status: "missing" },
      { id: "doc-009-11", entityType: "institution", name: "Accreditation Questionnaire", fileUrl: null, status: "missing" },
    ],
  },
  {
    id: "inv-010",
    name: "Crestline Family Office",
    email: "compliance@crestlinefo.com",
    phone: "+234 825 678 9012",
    investorPlatform: "Urbco Harbor",
    totalInvested: 0,
    totalPaid: 0,
    outstandingBalance: 0,
    paymentType: "one-time",
    assets: [],
    status: "active",
    createdAt: "2024-07-10T08:30:00Z",
    entityType: "family-office",
    investorTrack: "harbor",
    kycStatus: "remediation_required",
    kycSubmittedAt: "2024-07-18T12:00:00Z",
    kycVerifiedAt: null,
    kycRemediationItems: [
      "Proof of AUM / Asset Scale — bank reference is older than 6 months; upload a recent audited statement or bank reference",
    ],
    kycLastRemindedAt: null,
    kycProfile: {
      companyName: "Crestline Family Office Ltd",
      rcNumber: "RC-1310456",
      companyAddress: "8 Emerald Court, Ikoyi, Lagos",
      repName: "Adaeze Okonkwo",
      repEmail: "adaeze@crestlinefo.com",
    },
    kycDeclarations: {
      declaredAumRange: "$100M - $250M AUM",
      targetTrack: "harbor",
    },
    kycDocuments: [
      { id: "doc-010-1", entityType: "family-office", name: "Articles of Incorporation", fileUrl: "/kyc/crestline/articles.pdf", status: "approved" },
      { id: "doc-010-2", entityType: "family-office", name: "Trustee/Director Passports", fileUrl: "/kyc/crestline/trustee-ids.pdf", status: "approved" },
      { id: "doc-010-3", entityType: "family-office", name: "Proof of AUM / Asset Scale", fileUrl: "/kyc/crestline/old-bank-reference.pdf", status: "rejected", rejectReason: "Bank reference dated 8 months ago — provide a statement within 3 months" },
      { id: "doc-010-4", entityType: "family-office", name: "Beneficial Ownership (UBO)", fileUrl: "/kyc/crestline/ubo.pdf", status: "pending" },
    ],
  },
  {
    id: "inv-011",
    name: "Lagos Infrastructure Trust",
    email: "kyc@lagosinfrastructure.com",
    phone: "+234 826 789 0123",
    investorPlatform: "Urbco Foundry",
    totalInvested: 0,
    totalPaid: 0,
    outstandingBalance: 0,
    paymentType: "one-time",
    assets: [],
    status: "active",
    createdAt: "2024-04-28T09:15:00Z",
    entityType: "institution",
    investorTrack: "foundry",
    kycStatus: "verified",
    kycSubmittedAt: "2024-05-02T11:45:00Z",
    kycVerifiedAt: "2024-05-06T15:30:00Z",
    kycRemediationItems: [],
    kycLastRemindedAt: null,
    kycProfile: {
      companyName: "Lagos Infrastructure Trust",
      rcNumber: "RC-1476320",
      companyAddress: "1 Bourdillon Road, Ikoyi, Lagos",
      repName: "Funmi Balogun",
      repEmail: "f.balogun@lagosinfrastructure.com",
      institutionType: "Sovereign & Development Funds",
      structure: "SPV / Consortium",
      aumRange: "> ₦1T",
      horizon: "7+ years",
      sectors: ["Infrastructure", "Industrial & Logistics"],
      regulatoryStatus: "Regulated",
    },
    kycDeclarations: {},
    kycDocuments: [
      { id: "doc-011-1", entityType: "institution", name: "Articles of Incorporation", fileUrl: "/kyc/lagos-infra/articles.pdf", status: "approved" },
      { id: "doc-011-2", entityType: "institution", name: "Trustee/Director Passports", fileUrl: "/kyc/lagos-infra/trustee-ids.pdf", status: "approved" },
      { id: "doc-011-3", entityType: "institution", name: "Board Resolution Letter", fileUrl: "/kyc/lagos-infra/board-resolution.pdf", status: "approved" },
      { id: "doc-011-4", entityType: "institution", name: "Beneficial Ownership (UBO)", fileUrl: "/kyc/lagos-infra/ubo.pdf", status: "approved" },
      { id: "doc-011-5", entityType: "institution", name: "Corporate Registration & Tax ID", fileUrl: "/kyc/lagos-infra/cac-tin.pdf", status: "approved" },
      { id: "doc-011-6", entityType: "institution", name: "Officer / Director Identification", fileUrl: "/kyc/lagos-infra/officer-ids.pdf", status: "approved" },
      { id: "doc-011-7", entityType: "institution", name: "AML Compliance Certificate", fileUrl: "/kyc/lagos-infra/aml-cert.pdf", status: "approved" },
    ],
  },
];

export const mockNotifications = [
  {
    id: "notif-001",
    userId: "user-001",
    title: "New Lead Assigned",
    message: "Lead LEAD-002 has been assigned to cluster Lagos Alpha",
    type: "INFO",
    platform: "Urbco Foundry",
    read: false,
    createdAt: "2024-05-02T14:30:00Z",
  },
  {
    id: "notif-002",
    userId: "user-001",
    title: "Payment Received",
    message: "Payment of ₦25,000,000 received for transaction TXN-2024-001",
    type: "SUCCESS",
    platform: "Urbco Foundry",
    read: false,
    createdAt: "2024-05-01T10:15:00Z",
  },
  {
    id: "notif-003",
    userId: "user-001",
    title: "Commission Due",
    message: "3 commissions totaling ₦3,725,000 are due for payment",
    type: "WARNING",
    platform: "Urbco Foundry",
    read: true,
    createdAt: "2024-04-30T09:00:00Z",
  },
  {
    id: "notif-004",
    userId: "user-001",
    title: "Asset Published",
    message: "Ibeju-Lekki Land Parcel has been published successfully",
    type: "SUCCESS",
    platform: "Urbco Foundry",
    read: true,
    createdAt: "2024-05-01T08:00:00Z",
  },
  {
    id: "notif-005",
    userId: "user-001",
    title: "Urbco Harbor Project Funded",
    message: "Eko Atlantic Waterfront City reached 24% funding milestone",
    type: "INFO",
    platform: "Urbco Harbor",
    read: false,
    createdAt: "2024-06-20T10:00:00Z",
  },
  {
    id: "notif-006",
    userId: "user-001",
    title: "New Urbco Harbor Investor",
    message: "Adebayo Ogunlesi invested ₦50,000,000 in Eko Atlantic Waterfront City",
    type: "SUCCESS",
    platform: "Urbco Harbor",
    read: false,
    createdAt: "2024-06-15T14:00:00Z",
  },
];

export const mockDashboardKPIs = {
  totalRevenue: 10500000000,
  totalTransactions: 6,
  activeAssets: 6,
  totalLeads: 6,
  pendingLeads: 1,
  totalAgents: 7,
  totalCompanies: 3,
  revenueGrowth: 15.5,
  transactionGrowth: 12.3,
  leadConversionRate: 66.7,
  averageCommission: 931250,
  // Platform-specific KPIs
  foundryRevenue: 93000000,
  foundryTransactions: 4,
  foundryAssets: 4,
  foundryInvestors: 4,
  harborRevenue: 75000000,
  harborTransactions: 2,
  harborAssets: 2,
  harborInvestors: 3,
  // Backward compatibility keys
  buyOpsRevenue: 93000000,
  urbcoRevenue: 75000000,
};

export const mockDashboardCharts = {
  revenueByMonth: [
    { month: "Jan", revenue: 1500000000 },
    { month: "Feb", revenue: 1800000000 },
    { month: "Mar", revenue: 2200000000 },
    { month: "Apr", revenue: 2500000000 },
    { month: "May", revenue: 2500000000 },
  ],
  transactionsByStatus: [
    { status: "completed", count: 3 },
    { status: "pending", count: 1 },
    { status: "active", count: 2 },
  ],
  leadsBySource: [
    { source: "investor-app", count: 3 },
    { source: "agent", count: 1 },
    { source: "freelancer", count: 1 },
    { source: "team-lead", count: 1 },
  ],
  assetDistribution: [
    { type: "Off Plan", count: 1 },
    { type: "Completed", count: 1 },
    { type: "Under Construction", count: 1 },
    { type: "Land", count: 1 },
  ],
  assetByPlatform: [
    { platform: "Urbco Foundry", count: 4 },
    { platform: "Urbco Harbor", count: 2 },
  ],
  revenueByPlatform: [
    { platform: "Urbco Foundry", revenue: 93000000 },
    { platform: "Urbco Harbor", revenue: 75000000 },
  ],
};

export const mockInvoices = [
  {
    id: "inv-001",
    invoiceNumber: "INV-2024-001",
    clientName: "Robert Anderson",
    amount: 25000000,
    status: "paid",
    dueDate: "2024-05-01T10:00:00Z",
    createdAt: "2024-04-15T10:00:00Z",
    platform: "Urbco Foundry",
  },
  {
    id: "inv-002",
    invoiceNumber: "INV-2024-002",
    clientName: "Jennifer White",
    amount: 45000000,
    status: "paid",
    dueDate: "2024-04-28T10:00:00Z",
    createdAt: "2024-04-10T10:00:00Z",
    platform: "Urbco Foundry",
  },
  {
    id: "inv-003",
    invoiceNumber: "INV-2024-003",
    clientName: "Thomas Harris",
    amount: 15000000,
    status: "pending",
    dueDate: "2024-05-25T10:00:00Z",
    createdAt: "2024-04-25T10:00:00Z",
    platform: "Urbco Foundry",
  },
  {
    id: "inv-004",
    invoiceNumber: "INV-2024-004",
    clientName: "Adebayo Ogunlesi",
    amount: 50000000,
    status: "pending",
    dueDate: "2024-07-15T10:00:00Z",
    createdAt: "2024-06-01T10:00:00Z",
    platform: "Urbco Harbor",
  },
];

export const mockReports = {
  sales: {
    totalSales: 168000000,
    totalCommission: 6725000,
    averageDealSize: 28000000,
    topPerformingAsset: "Lekki Phase 1 Estate",
    topPerformingAgent: "David Wilson",
    salesByMonth: [
      { month: "Jan", sales: 15000000 },
      { month: "Feb", sales: 18000000 },
      { month: "Mar", sales: 22000000 },
      { month: "Apr", sales: 20000000 },
      { month: "May", sales: 18000000 },
      { month: "Jun", sales: 50000000 },
      { month: "Jul", sales: 25000000 },
    ],
    salesByPlatform: [
      { platform: "Urbco Foundry", sales: 93000000, count: 4 },
      { platform: "Urbco Harbor", sales: 75000000, count: 2 },
    ],
  },
  assets: {
    totalAssets: 6,
    activeAssets: 6,
    totalValue: 38500000000,
    averageROI: 26.5,
    assetsByType: [
      { type: "Off Plan", count: 3, value: 15000000000 },
      { type: "Completed", count: 1, value: 8500000000 },
      { type: "Under Construction", count: 1, value: 10000000000 },
      { type: "Land", count: 1, value: 5000000000 },
    ],
    assetsByPlatform: [
      { platform: "Urbco Foundry", count: 4, value: 28500000000 },
      { platform: "Urbco Harbor", count: 2, value: 15000000000 },
    ],
  },
  investments: {
    totalInvestments: 168000000,
    activeInvestors: 7,
    averageInvestment: 24000000,
    totalReturns: 33600000,
    roi: 20,
    investmentsByPlatform: [
      { platform: "Urbco Foundry", total: 93000000, investors: 4 },
      { platform: "Urbco Harbor", total: 75000000, investors: 3 },
    ],
  },
  commissions: {
    totalCommissions: 6725000,
    paidCommissions: 1800000,
    unpaidCommissions: 4925000,
    averageCommissionRate: 3.2,
    commissionsByPlatform: [
      { platform: "Urbco Foundry", total: 3725000, paid: 1800000, unpaid: 1925000 },
      { platform: "Urbco Harbor", total: 3000000, paid: 0, unpaid: 3000000 },
    ],
    commissionsByAgent: mockAgents.map((agent) => ({
      agentId: agent.id,
      agentName: agent.name,
      totalCommission: agent.totalCommission,
      paidCommission: agent.status === "ACTIVE" ? agent.totalCommission * 0.6 : 0,
      unpaidCommission: agent.status === "ACTIVE" ? agent.totalCommission * 0.4 : 0,
    })),
  },
  performance: {
    topAgents: mockAgents
      .filter((a) => a.role === "AGENT" || a.role === "TEAM_LEAD")
      .sort((a, b) => b.performance - a.performance)
      .slice(0, 5),
    topClusters: mockClusters
      .sort((a, b) => b.totalRevenue - a.totalRevenue)
      .slice(0, 3),
    conversionRate: 66.7,
    averageClosingTime: 14,
    performanceByPlatform: [
      { platform: "Urbco Foundry", conversionRate: 75, closingTime: 10 },
      { platform: "Urbco Harbor", conversionRate: 45, closingTime: 21 },
    ],
  },
};
